version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./carbon-project-hanbat-5cbc71a30dff.json:/app/credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - MONGO_URL=mongodb://mongodb:27017
      - MONGO_DB_NAME=recycling_db
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:8000
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
